### PR TITLE
raise account changed event property on logout as well

### PR DESCRIPTION
**Pull request by wpeter-sfdc**
@kchitalia @smcnulty-sfdc

### CODE REVIEW

**Comment by jbernoudy** [comment]
:+1:

**Comment by kchitalia** [comment]
@bhariharan Do we raise events for user logged in and user logged out in a similar fashion on Android too(in Account Manager)?

**Comment by bhariharan** [comment]
```Android:```

We broadcast an event when user switch occurs. When a new user logs in, that user automatically becomes the current user, so a user switch event will be broadcast. Similarly, when logout occurs, we automatically switch to an existing user if one is present, or display the list of existing users if more than one is present, so once the switch is complete, the user switch event will be broadcast again. There are no specific login or logout events broadcast, only user switch events.

```iOS:```
Delegate callbacks are available for user logout and user switch events, so an app can handle both scenarios.

**Comment by kchitalia** [comment]
The events that are broadcasted when a token is refreshed/revoked are different from the user switch, right?

**Comment by bhariharan** [comment]
Yes - token revocation and token refresh are different events.

**Comment by kchitalia** [comment]
These changes look fine then. I'll add a story for token refresh and token revoke events. Thanks @bhariharan for clarifying a lot of the details.

**Comment by bhariharan** [comment]
The events for token revocation and refresh are ```Android``` only IIRC.

**Pull request merged**
