### PR TITLE
remove cached version of project.lock.json that should have been ignored

### PR DESCRIPTION
**Pull request by wpeter-sfdc**
somewhere along the line this file got added to source control, but it shouldn't be there, this is an auto generated file that changes frequently.

@bhariharan @kchitalia

### CODE REVIEW

**Comment by bhariharan** [comment]
Oh boy! Thanks @wpeter-sfdc!

**Comment by kchitalia** [comment]
@wpeter-sfdc You will have to add it to the gitignore file as well.

**Comment by jbernoudy** [comment]
@kchitalia  It's already there

**Comment by wpeter-sfdc** [comment]
@kchitalia 

Jesse is correct, the project.lock.json files are already ignored, I added them to the ignore list back in August of last year... but I forgot the important step of removing the cached version, so to fix it I ran `git rm -r --cached <path to file>` - even if something is in the ignore list if it was already added to source control you have to explicitly remove the cached version... my mistake from 8 months ago :)

**Comment by wpeter-sfdc** [comment]
btw, I didn't realize it was from my commit months ago, I just found the [guilty commit here](https://github.com/forcedotcom/SalesforceMobileSDK-Windows/commit/8d7cef6e64c7b59d318f4df739b15ca7adf38fd6)

Looks like a few other projects may have the cached lock file around - Hybrid, Hybrid.SmartStore, and Hybrid.SmartSync

I'll fix those too since I missed them in the first pass (we aren't consuming any of the hybrid projects so that's why I missed them)

**Pull request merged**
