### PR TITLE
Fixing a bug where SmartStore was calling ToString on its return objects

### PR DESCRIPTION
**Pull request by jhorstsf**

### CODE REVIEW

**Comment by jhorstsf** [comment]
@wpeter-sfdc @kchitalia

**Comment by kchitalia** [comment]
When you call a ToString(), does it not allow you to convert it to a jObject?

**Comment by wpeter-sfdc** [comment]
:+1:

**Comment by jhorstsf** [comment]
@kchitalia - I could but I wanted to make it consistent with what was being returned for Upsert. The problem is sometimes the smart store was returning data serialized and other times it was returning it as an object.

**Comment by kchitalia** [comment]
Makes sense. Its easier to work with objects.

**Comment by kchitalia** [comment]
:+1:

**Pull request merged**
