### PR TITLE
update the readme file to reflect the change for creating application using template script

### PR DESCRIPTION
**Pull request by helenren**
@kchitalia

### CODE REVIEW

**Comment by bhariharan** [comment]
👍

**Comment by kchitalia** [comment]
Do we need the test.txt file? Looks like it was added by mistake?

**Comment by kchitalia** [comment]
@helenren There is a step on the Readme page that talks about a pre-built template(Step 5). We should remove that  along with these changes.

**Comment by kchitalia** [comment]
👍

**Pull request merged**
