### PR TITLE
Resync only new data

### PR DESCRIPTION
**Pull request by smcnulty-sfdc**
Changelist adds ability to resync only new data, skipping unchanged items from server side.

### CODE REVIEW

**Comment by bhariharan** [comment]
Looks good to me.

**Comment by wmathurin** [comment]
Looks good. Do you have unit tests for smartsync?

**Comment by khawkins** [comment]
:+1:

**Comment by smcnulty-sfdc** [comment]
@wmathurin those are in another review. Had some issues/stuff to get going with the unit tests going against a live instance.

**Pull request merged**
