### PR TITLE
use 4.2.0 as the next version before 5.0.0

### PR DESCRIPTION
**Pull request by helenren**
Update the template app to adopt the recent changes for upgrade.

### CODE REVIEW

**Comment by bhariharan** [comment]
Our latest release is `4.3.0`.

**Comment by wmathurin** [comment]
I don't think there was a 4.2 on windows.

**Comment by helenren** [comment]
No, we don't. The version on master is 4.0.0.

**Comment by bhariharan** [comment]
@helenren Since this is for the upcoming release, we should set version number to `5.0.0`.

**Comment by helenren** [comment]
as we discussed yesterday, this time will just make it version 4.2 and then publish this version to nuget.ort, while not push to master, need more time to stabilize and there are some other works for 5.0. After this publish, we will bump to 5.0.

**Pull request merged**
