### PR TITLE
add support for network call cancellation

### PR DESCRIPTION
**Pull request by jhsfdc**
@kchitalia @wpeter-sfdc

### CODE REVIEW

**Comment by bhariharan** [comment]
Seems fine to me. Could we add some tests?

**Comment by kchitalia** [comment]
Please update/add tests around this.

**Comment by jhsfdc** [comment]
There's not really much to test here, we are just adding the optional cancellation token that HttpClient accepts to the exposing rest interfaces that sit on top of HttpClient. All we would be testing would be the .Net HttpClient token cancellation logic (which is Microsoft's job to do :))

**Comment by bhariharan** [comment]
:+1:

**Comment by kchitalia** [comment]
:+1:

**Pull request merged**
