### PR TITLE
add mvvmlight 5.2 nuget package

### PR DESCRIPTION
**Pull request by wpeter-sfdc**
missed this with my PR yesterday, s1 still needs the packages checked in when consuming

@bhariharan 
@kchitalia

### CODE REVIEW

**Comment by kchitalia** [comment]
@wpeter-sfdc Question for you, Are we keeping the binaries? Does the S1 Windows team need them?

**Comment by wpeter-sfdc** [comment]
@kchitalia Yes, for now we still do.

**Comment by kchitalia** [comment]
Ok, cool. Do you guys need Newtonsoft.Json  and ServiceLocator as well?

**Comment by wpeter-sfdc** [comment]
those are already there

**Comment by kchitalia** [comment]
Perfect. 👍

**Pull request merged**
