### PR TITLE
Removing sensitive data from log lines

### PR DESCRIPTION
**Pull request by helenren**

### CODE REVIEW

**Comment by bhariharan** [comment]
@helenren Are there upgrade steps required for existing apps with users logged in using an older version of ```Mobile SDK``` (```MD5```) to the newer version of ```Mobile SDK``` (```SHA256```)?

**Comment by bhariharan** [comment]
👍

**Comment by helenren** [comment]
I think we should be fine not to have a upgrade flow for MD5 change, since actually the mobile integration is not enabled by connected application for Windows. And as I know that s1 windows hasn't support pincode yet.

**Comment by bhariharan** [comment]
@helenren Apps built on ```Mobile SDK Windows``` will require connected apps too. We rely on ```clientId``` and ```callbackUrl``` to identify the app and perform authentication (see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Windows/blob/master/SalesforceSDK/Core/Auth/OAuth2.cs)). We do support PIN code on ```Mobile SDK Windows``` too (see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Windows/blob/master/SalesforceSDK/Core/Auth/OAuth2.cs)). Also, upgrade has nothing to do with whether PIN code exists or not. If the authentication credentials (tokens) are stored encrypted with the old cipher, attempting to decrypt with the new cipher will throw an exception and log users out, even if the encryption key is the same.

**Comment by helenren** [comment]
Since we need to take care the upgrade scenario to make sure no break for user, revert the MD5 change and do the change and upgrade flow together in another work.

**Comment by bhariharan** [comment]
👍

**Pull request merged**
